#!/usr/bin/env bash

# Copyright (C) 2013 ClearType Team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

pa=packages
app=apps
dh=drawable-hdpi
dx=drawable-xhdpi
mh=mipmap-hdpi
mx=mipmap-xhdpi

echo 'ClearOS'

cd SystemUI
cp res/$dh/*.png ../../../frameworks/base/packages/SystemUI/res/$dh/
cp res/$dx/*.png ../../../frameworks/base/packages/SystemUI/res/$dx/
cp res/layout/status_bar_recent_item.xml ../../../frameworks/base/packages/SystemUI/res/layout/
cp res/values/*.xml ../../../frameworks/base/packages/SystemUI/res/values/
cp src/recent/*.java ../../../frameworks/base/packages/SystemUI/src/com/android/systemui/recent/

cd ..

cd framework
cp $dh/*.png ../../../frameworks/base/core/res/res/$dh/
cp $dx/*.png ../../../frameworks/base/core/res/res/$dx/
cd ..

cd $dh
cp ic_launcher_browser.png ../../../$pa/$app/Browser/res/$mh/
cp ic_launcher_calendar.png ../../../$pa/$app/Calendar/res/$mh/
cp ic_launcher_camera.png ../../../$pa/$app/Camera/res/$mh/
cp ic_launcher_contacts.png ../../../$pa/$app/Contacts/res/$mh/
cp ic_launcher_phone.png ../../../$pa/$app/Contacts/res/$mh/
cp ic_launcher_email.png ../../../$pa/$app/Email/res/$mh/
cp ic_launcher_gallery.png ../../../$pa/$app/Gallery2/res/$mh/
cp ic_launcher_smsmms.png ../../../$pa/$app/Mms/res/$mh/
cp ic_launcher_contacts.png ../../../$pa/$app/Mms/res/$mh/
cp ic_launcher_phone.png ../../../$pa/$app/Phone/res/$mh/
cp ic_launcher_contacts.png ../../../$pa/$app/Phone/res/$mh/
cp ic_launcher_settings.png ../../../$pa/$app/Settings/res/$mh/
cp ic_launcher_soundrecorder.png ../../../$pa/$app/SoundRecorder/res/$dh/
cp ic_allapps.png ../../../$pa/$app/Trebuchet/res/$dh/
cp ic_allapps_pressed.png ../../../$pa/$app/Trebuchet/res/$dh/
cp ic_launcher_home.png ../../../$pa/$app/Trebuchet/res/$mh/
cp ic_launcher_download.png ../../../$pa/providers/DownloadProvider/ui/res/$mh

cd ..


cd $dx
cp ic_launcher_browser.png ../../../$pa/$app/Browser/res/$mx/
cp ic_launcher_calendar.png ../../../$pa/$app/Calendar/res/$mx/
cp ic_launcher_camera.png ../../../$pa/$app/Camera/res/$mx/
cp ic_launcher_contacts.png ../../../$pa/$app/Contacts/res/$mx/
cp ic_launcher_phone.png ../../../$pa/$app/Contacts/res/$mx/
cp ic_launcher_email.png ../../../$pa/$app/Email/res/$mx/
cp ic_launcher_gallery.png ../../../$pa/$app/Gallery2/res/$mx/
cp ic_launcher_smsmms.png ../../../$pa/$app/Mms/res/$mx/
cp ic_launcher_contacts.png ../../../$pa/$app/Mms/res/$mx/
cp ic_launcher_phone.png ../../../$pa/$app/Phone/res/$mx/
cp ic_launcher_contacts.png ../../../$pa/$app/Phone/res/$mx/
cp ic_launcher_settings.png ../../../$pa/$app/Settings/res/$mx/
cp ic_allapps.png ../../../$pa/$app/Trebuchet/res/$dx/
cp ic_allapps_pressed.png ../../../$pa/$app/Trebuchet/res/$dx/
cp ic_launcher_home.png ../../../$pa/$app/Trebuchet/res/$mx/
cp ic_launcher_download.png ../../../$pa/providers/DownloadProvider/ui/res/$mx


cd ..
